learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('learning_logs.urls')),
    path('users/',include('users.urls')),
]

learning_logs/urls.py
"""Схемы URL для learning_logs."""

from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    path('',views.index,name='index'),
    path('topics/',views.topics,name='topics'),
    path('topics/<int:topic_id>/',views.topic,name="topic"),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>/',views.new_entry,name="new_entry"),
    path('edit_entry/<int:entry_id>/',views.edit_entry,name="edit_entry"),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/',views.register,name="register"),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    owner = models.ForeignKey(User,on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

class Entry(models.Model):
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        else:
            return self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text':''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields  = ['text']
        labels = {'text' : 'Entry'}
        widgets = {'text' : forms.Textarea()}

learning_logs/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.http import Http404

def index(request):
    return render(request,'learning_logs/index.html')

@login_required
def topics(request):
    topics = Topic.objects.filter(owner=request.user).order_by("date_added")
    context = {'topics' : topics}
    return render(request,'learning_logs/topics.html',context)

@login_required
def topic(request,topic_id):
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {"topic" : topic, "entries" : entries}

    return render(request, 'learning_logs/topic.html', context)

@login_required    
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')
        
    context = {'form': form}
    return render(request,'learning_logs/new_topic.html',context)

@login_required
def new_entry(request,topic_id):
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic',topic_id=topic_id)
    context = {'topic' : topic, 'form' : form}
    return render(request,'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request,entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != "POST":
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry,data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic',topic_id = topic.id)
        
    context = {'entry':entry,'topic':topic,'form' : form}
    return render(request,'learning_logs/edit_entry.html',context)

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):

    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            login(request,new_user)
            return redirect('learning_logs:index')
        
    context = {'form' : form}
    return render(request, 'registration/register.html',context)

# Create your views here.

learning_logs/templates/learning_logs/base.html
{%load bootstrap4%}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="uft-8">
    <meta name="viewport" content="width=device-width,inital-scale=1,shrick-to-fit=no">
    <title>Learning Log</title>
    <link rel="icon" href="https://sun9-4.userapi.com/impg/IOEa1iqdTdflcXO-uU8TX2RtsEIJBAeDc0M86g/nYwjmcQQwEE.jpg?size=512x512&quality=95&sign=be33986136f161d2aae0cfbd9a5819cb&type=album">

    {% bootstrap_css%}
    {% bootstrap_javascript jquery='full' %}
  </head>
  <body>

      <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
          Learning Log
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
         data-target="#navbarCollapse" aria-controls="navbarCollapse"
         aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span></button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class=" nav-link" href="{% url 'learning_logs:topics'%}">Topics</a>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated%}
              <li class="nav-item">
                <span class="navbar-text">{{user.username}} |</span>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
              </li>
            {%else%}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register'%}">Register</a>
              </li> 
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login'%}">Log in</a>
              </li>
            
            {%endif%}
          </ul> 
        </div>
      </nav>

      <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
          {% block page_header %}{% endblock page_header%}
        </div>
        <div>
          {% block content %}{% endblock content %}
        </div>
      </main>
  </body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html'%}
{% load bootstrap4 %}

{%block page_header%}

{%endblock page_header%}
  <h1><a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></h1>
{% block content %}


<h3>Edit entry :</h3>

<form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
    {%csrf_token%}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="sumbit">save changes</button>
    {%endbuttons%}
</form>

{%endblock content%}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <div class="jumbotron" >
    {% if user.is_authenticated%}
    <h1 class="display-4" style="text-align: center;">Hello,{{user.username}}</h1>
    <p class="lead">New knowledge is still waiting for you! <br> <br> We remind you that our website helps you keep a diary on the topics you are studying. <br>
       Just add an interesting topic and feed it with new entries.</p>
    {%else%}
    <h1 class="display-4" style="text-align: center;">Hello,guest</h1>
    <p class="lead">Register on our website faster to become the coolest and most advanced smart guy.<br>We`ll help you:</p>
      <ul class="lead">
        <li>Securely save your scientific topics</li>
        <li>Add new entries to your topics</li>
        <li>Hide your entries from other users</li>
        <li>And much much more</li>
      </ul>
      <p class="lead">We are waiting for you &#59;&#41;</p>
      <a class="btn btn-lg btn-primary" href="{%url 'users:register'%}" role="button"> Register &raquo;</a>
    {%endif%}
  </div>
  
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{%block page_header%}
  <h2><a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></h2>
{%endblock page_header%}

{%block content%}
<h3>Add a new entry</h3>

<form action="{% url 'learning_logs:new_entry' topic.id%}" method="post">
    {% csrf_token %}
    {% bootstrap_form form%}
    {% buttons %}
      <button name="sumbit" class="btn btn-primary">add entry</button>
    {%endbuttons%}
</form>

{%endblock content%}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}

{%block page_header%}
  <h2> Add a new topic</h2>
{%endblock page_header%}

{% block content %}

<form action="{% url 'learning_logs:new_topic'%}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form%}
    {% buttons %}
      <button class="btn btn-primary" name="sumbit">add topic</button>
    {%endbuttons%}
</form>

{%endblock content%}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html'%}
{% load bootstrap4%}

{%block page_header%}
  <h2>{{topic}}</h2>
{%endblock page_header%}

{% block content %}

  <ul class="list-group">
    {%for entry in entries%}
    <li class="list-group-item">
      <p>
        {{entry.date_added|date:'M d, Y H:i' }}
        <a href="{% url 'learning_logs:edit_entry' entry.id%}" style="font-size:16px">Edit entry</a>
      </p>
      <p style="word-wrap: break-word; ">{{entry.text}}</p>
    </li>
    {%empty%}
    <li>There are no entries for this topic yet</li>
    {%endfor%}
  </ul>

  <p>
    <a class="btn btn-lg btn-primary" href="{%url 'learning_logs:new_entry' topic.id %}" role="button"> Add entry</a>
  </p>
{%endblock content%}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{%block page_header%}
  <div style="display: flex;">
    <h2>Topics</h2>
    
  </div>
{%endblock page_header%}

{%block content%}

{%for topic in topics%}
  <div style="display: flex;">    
    <h3>
      <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }} </a>
    </h3>
  </div>
{% empty %}
  <h3>No topics have been added yet</h3>
{% endfor %}


<p><a class="btn btn-lg btn-primary" href="{%url 'learning_logs:new_topic'%}" role="button"> Add topic</a></p>
{%endblock content%}